@Test public void verifyFailures() throws Exception {
assertThat(output,containsString("Tests run: 5,  Failures: 3"));
}