@Test(expected=RuntimeException.class) public void testUpdateIdThrow() throws Exception {
}