@Test(expected=RuntimeException.class) public void testSetObjectCacheThrow() throws Exception {
}