@Test(expected=RuntimeException.class) public void testCallBatchTasksThrow() throws Exception {
}