@Test(expected=RuntimeException.class) public void testUpdateThrow() throws Exception {
}